POST http://localhost:8000/create-blog
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2Y2VkNDI1NGVhNzhjODkxOWZkZGJhZiIsImVtYWlsIjoic3VyZXNoYWxhYmFuaTI3ODVAZ21haWwuY29tIiwiaWF0IjoxNzI0ODMwNzU3LCJleHAiOjE3MjQ4MzQzNTd9.xmP6U1B88NO5xJA2e0HW_Vy3oNimMwPEgQLOY-84QtM

{
    "title":"Gojo Satorus",
    "banner":"https://example.coms",
    "desc":"khkhlkssh",
    "content":{
        "blocks":[1,3]
    },
    "tags":["tags1","tag","sdfsd"]
}